// @ts-nocheck
import * as __fd_glob_67 from "../content/docs/zh/editor/editor-panels/ui-panel/canvas-settings.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/zh/editor/editor-panels/ui-panel/add-interaction.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/zh/editor/editor-panels/scene-panel/post-processing.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/zh/editor/editor-panels/model-panel/debug-tools.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/zh/editor/editor-panels/marker-panel/add-interaction.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/en/editor/editor-panels/ui-panel/canvas-settings.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/en/editor/editor-panels/ui-panel/add-interaction.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/en/editor/editor-panels/scene-panel/post-processing.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/en/editor/editor-panels/model-panel/debug-tools.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/en/editor/editor-panels/marker-panel/add-interaction.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/zh/editor/main-ui/index.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/zh/editor/editor-panels/index.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/en/editor/main-ui/index.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/en/editor/editor-panels/index.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/zh/step-by-step-workflow/index.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/zh/step-by-step-workflow/9-save-and-preview.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/zh/step-by-step-workflow/8-ui-pages-and-interactions.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/zh/step-by-step-workflow/7-add-markers.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/zh/step-by-step-workflow/6-lighting.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/zh/step-by-step-workflow/5-camera-behaviour.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/zh/step-by-step-workflow/4-adjust-model-layout.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/zh/step-by-step-workflow/3-upload-models.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/zh/step-by-step-workflow/2-project-settings.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/zh/step-by-step-workflow/10-publish-and-share.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/zh/step-by-step-workflow/1-create-project.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/zh/project-center/project-list.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/zh/project-center/index.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/zh/open-api/index.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/en/step-by-step-workflow/index.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/en/step-by-step-workflow/9-save-and-preview.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/en/step-by-step-workflow/8-ui-pages-and-interactions.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/en/step-by-step-workflow/7-add-markers.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/en/step-by-step-workflow/6-lighting.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/en/step-by-step-workflow/5-camera-behaviour.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/en/step-by-step-workflow/4-adjust-model-layout.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/en/step-by-step-workflow/3-upload-models.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/en/step-by-step-workflow/2-project-settings.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/en/step-by-step-workflow/10-publish-and-share.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/en/step-by-step-workflow/1-create-project.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/zh/editor/index.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/en/project-center/project-list.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/en/project-center/index.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/en/open-api/index.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/en/editor/index.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/zh/platform-concepts.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/zh/index.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/en/platform-concepts.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/en/index.mdx?collection=docs"
import { default as __fd_glob_19 } from "../content/docs/zh/editor/editor-panels/ui-panel/meta.json?collection=docs"
import { default as __fd_glob_18 } from "../content/docs/zh/editor/editor-panels/scene-panel/meta.json?collection=docs"
import { default as __fd_glob_17 } from "../content/docs/zh/editor/editor-panels/model-panel/meta.json?collection=docs"
import { default as __fd_glob_16 } from "../content/docs/zh/editor/editor-panels/marker-panel/meta.json?collection=docs"
import { default as __fd_glob_15 } from "../content/docs/en/editor/editor-panels/ui-panel/meta.json?collection=docs"
import { default as __fd_glob_14 } from "../content/docs/en/editor/editor-panels/scene-panel/meta.json?collection=docs"
import { default as __fd_glob_13 } from "../content/docs/en/editor/editor-panels/model-panel/meta.json?collection=docs"
import { default as __fd_glob_12 } from "../content/docs/en/editor/editor-panels/marker-panel/meta.json?collection=docs"
import { default as __fd_glob_11 } from "../content/docs/zh/editor/editor-panels/meta.json?collection=docs"
import { default as __fd_glob_10 } from "../content/docs/en/editor/editor-panels/meta.json?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/zh/step-by-step-workflow/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/zh/project-center/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/zh/open-api/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/zh/editor/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/en/step-by-step-workflow/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/en/project-center/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/en/open-api/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/en/editor/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/zh/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/en/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"en/meta.json": __fd_glob_0, "zh/meta.json": __fd_glob_1, "en/editor/meta.json": __fd_glob_2, "en/open-api/meta.json": __fd_glob_3, "en/project-center/meta.json": __fd_glob_4, "en/step-by-step-workflow/meta.json": __fd_glob_5, "zh/editor/meta.json": __fd_glob_6, "zh/open-api/meta.json": __fd_glob_7, "zh/project-center/meta.json": __fd_glob_8, "zh/step-by-step-workflow/meta.json": __fd_glob_9, "en/editor/editor-panels/meta.json": __fd_glob_10, "zh/editor/editor-panels/meta.json": __fd_glob_11, "en/editor/editor-panels/marker-panel/meta.json": __fd_glob_12, "en/editor/editor-panels/model-panel/meta.json": __fd_glob_13, "en/editor/editor-panels/scene-panel/meta.json": __fd_glob_14, "en/editor/editor-panels/ui-panel/meta.json": __fd_glob_15, "zh/editor/editor-panels/marker-panel/meta.json": __fd_glob_16, "zh/editor/editor-panels/model-panel/meta.json": __fd_glob_17, "zh/editor/editor-panels/scene-panel/meta.json": __fd_glob_18, "zh/editor/editor-panels/ui-panel/meta.json": __fd_glob_19, }, {"en/index.mdx": __fd_glob_20, "en/platform-concepts.mdx": __fd_glob_21, "zh/index.mdx": __fd_glob_22, "zh/platform-concepts.mdx": __fd_glob_23, "en/editor/index.mdx": __fd_glob_24, "en/open-api/index.mdx": __fd_glob_25, "en/project-center/index.mdx": __fd_glob_26, "en/project-center/project-list.mdx": __fd_glob_27, "zh/editor/index.mdx": __fd_glob_28, "en/step-by-step-workflow/1-create-project.mdx": __fd_glob_29, "en/step-by-step-workflow/10-publish-and-share.mdx": __fd_glob_30, "en/step-by-step-workflow/2-project-settings.mdx": __fd_glob_31, "en/step-by-step-workflow/3-upload-models.mdx": __fd_glob_32, "en/step-by-step-workflow/4-adjust-model-layout.mdx": __fd_glob_33, "en/step-by-step-workflow/5-camera-behaviour.mdx": __fd_glob_34, "en/step-by-step-workflow/6-lighting.mdx": __fd_glob_35, "en/step-by-step-workflow/7-add-markers.mdx": __fd_glob_36, "en/step-by-step-workflow/8-ui-pages-and-interactions.mdx": __fd_glob_37, "en/step-by-step-workflow/9-save-and-preview.mdx": __fd_glob_38, "en/step-by-step-workflow/index.mdx": __fd_glob_39, "zh/open-api/index.mdx": __fd_glob_40, "zh/project-center/index.mdx": __fd_glob_41, "zh/project-center/project-list.mdx": __fd_glob_42, "zh/step-by-step-workflow/1-create-project.mdx": __fd_glob_43, "zh/step-by-step-workflow/10-publish-and-share.mdx": __fd_glob_44, "zh/step-by-step-workflow/2-project-settings.mdx": __fd_glob_45, "zh/step-by-step-workflow/3-upload-models.mdx": __fd_glob_46, "zh/step-by-step-workflow/4-adjust-model-layout.mdx": __fd_glob_47, "zh/step-by-step-workflow/5-camera-behaviour.mdx": __fd_glob_48, "zh/step-by-step-workflow/6-lighting.mdx": __fd_glob_49, "zh/step-by-step-workflow/7-add-markers.mdx": __fd_glob_50, "zh/step-by-step-workflow/8-ui-pages-and-interactions.mdx": __fd_glob_51, "zh/step-by-step-workflow/9-save-and-preview.mdx": __fd_glob_52, "zh/step-by-step-workflow/index.mdx": __fd_glob_53, "en/editor/editor-panels/index.mdx": __fd_glob_54, "en/editor/main-ui/index.mdx": __fd_glob_55, "zh/editor/editor-panels/index.mdx": __fd_glob_56, "zh/editor/main-ui/index.mdx": __fd_glob_57, "en/editor/editor-panels/marker-panel/add-interaction.mdx": __fd_glob_58, "en/editor/editor-panels/model-panel/debug-tools.mdx": __fd_glob_59, "en/editor/editor-panels/scene-panel/post-processing.mdx": __fd_glob_60, "en/editor/editor-panels/ui-panel/add-interaction.mdx": __fd_glob_61, "en/editor/editor-panels/ui-panel/canvas-settings.mdx": __fd_glob_62, "zh/editor/editor-panels/marker-panel/add-interaction.mdx": __fd_glob_63, "zh/editor/editor-panels/model-panel/debug-tools.mdx": __fd_glob_64, "zh/editor/editor-panels/scene-panel/post-processing.mdx": __fd_glob_65, "zh/editor/editor-panels/ui-panel/add-interaction.mdx": __fd_glob_66, "zh/editor/editor-panels/ui-panel/canvas-settings.mdx": __fd_glob_67, });