// @ts-nocheck
import * as __fd_glob_65 from "../content/docs/zh/editor/editor-panels/model-panel/model-settings.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/zh/editor/editor-panels/model-panel/debug-tools.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/zh/editor/editor-panels/model-panel/asset-management.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/zh/editor/editor-panels/scene-panel/project-settings.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/zh/editor/editor-panels/scene-panel/post-processing.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/zh/editor/editor-panels/scene-panel/lighting.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/zh/editor/editor-panels/scene-panel/camera-controller.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/zh/editor/editor-panels/ui-panel/page-and-component-management.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/zh/editor/editor-panels/ui-panel/canvas-settings.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/zh/editor/editor-panels/ui-panel/add-interaction.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/en/editor/editor-panels/scene-panel/project-settings.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/en/editor/editor-panels/scene-panel/post-processing.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/en/editor/editor-panels/scene-panel/lighting.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/en/editor/editor-panels/scene-panel/camera-controller.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/en/editor/editor-panels/model-panel/model-settings.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/en/editor/editor-panels/model-panel/debug-tools.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/en/editor/editor-panels/model-panel/asset-management.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/zh/editor/editor-panels/marker-panel/add-marker.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/zh/editor/editor-panels/marker-panel/add-interaction.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/en/editor/editor-panels/ui-panel/page-and-component-management.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/en/editor/editor-panels/ui-panel/canvas-settings.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/en/editor/editor-panels/ui-panel/add-interaction.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/en/editor/editor-panels/marker-panel/add-marker.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/en/editor/editor-panels/marker-panel/add-interaction.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/zh/editor/main-ui/index.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/zh/editor/editor-panels/index.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/en/editor/main-ui/index.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/en/editor/editor-panels/index.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/zh/open-api/index.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/zh/editor/project-actions.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/zh/editor/index.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/zh/project-center/project-list.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/zh/project-center/project-actions.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/zh/project-center/index.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/zh/project-center/create-project.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/en/project-center/project-list.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/en/project-center/project-actions.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/en/project-center/index.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/en/project-center/create-project.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/en/open-api/index.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/en/editor/project-actions.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/en/editor/index.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/zh/platform-concepts.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/zh/index.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/zh/end-to-end-workflow.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/en/platform-concepts.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/en/index.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/en/end-to-end-workflow.mdx?collection=docs"
import { default as __fd_glob_17 } from "../content/docs/zh/editor/editor-panels/ui-panel/meta.json?collection=docs"
import { default as __fd_glob_16 } from "../content/docs/zh/editor/editor-panels/marker-panel/meta.json?collection=docs"
import { default as __fd_glob_15 } from "../content/docs/zh/editor/editor-panels/scene-panel/meta.json?collection=docs"
import { default as __fd_glob_14 } from "../content/docs/zh/editor/editor-panels/model-panel/meta.json?collection=docs"
import { default as __fd_glob_13 } from "../content/docs/en/editor/editor-panels/ui-panel/meta.json?collection=docs"
import { default as __fd_glob_12 } from "../content/docs/en/editor/editor-panels/scene-panel/meta.json?collection=docs"
import { default as __fd_glob_11 } from "../content/docs/en/editor/editor-panels/model-panel/meta.json?collection=docs"
import { default as __fd_glob_10 } from "../content/docs/en/editor/editor-panels/marker-panel/meta.json?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/zh/editor/editor-panels/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/en/editor/editor-panels/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/zh/project-center/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/zh/open-api/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/zh/editor/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/en/project-center/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/en/open-api/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/en/editor/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/zh/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/en/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"en/meta.json": __fd_glob_0, "zh/meta.json": __fd_glob_1, "en/editor/meta.json": __fd_glob_2, "en/open-api/meta.json": __fd_glob_3, "en/project-center/meta.json": __fd_glob_4, "zh/editor/meta.json": __fd_glob_5, "zh/open-api/meta.json": __fd_glob_6, "zh/project-center/meta.json": __fd_glob_7, "en/editor/editor-panels/meta.json": __fd_glob_8, "zh/editor/editor-panels/meta.json": __fd_glob_9, "en/editor/editor-panels/marker-panel/meta.json": __fd_glob_10, "en/editor/editor-panels/model-panel/meta.json": __fd_glob_11, "en/editor/editor-panels/scene-panel/meta.json": __fd_glob_12, "en/editor/editor-panels/ui-panel/meta.json": __fd_glob_13, "zh/editor/editor-panels/model-panel/meta.json": __fd_glob_14, "zh/editor/editor-panels/scene-panel/meta.json": __fd_glob_15, "zh/editor/editor-panels/marker-panel/meta.json": __fd_glob_16, "zh/editor/editor-panels/ui-panel/meta.json": __fd_glob_17, }, {"en/end-to-end-workflow.mdx": __fd_glob_18, "en/index.mdx": __fd_glob_19, "en/platform-concepts.mdx": __fd_glob_20, "zh/end-to-end-workflow.mdx": __fd_glob_21, "zh/index.mdx": __fd_glob_22, "zh/platform-concepts.mdx": __fd_glob_23, "en/editor/index.mdx": __fd_glob_24, "en/editor/project-actions.mdx": __fd_glob_25, "en/open-api/index.mdx": __fd_glob_26, "en/project-center/create-project.mdx": __fd_glob_27, "en/project-center/index.mdx": __fd_glob_28, "en/project-center/project-actions.mdx": __fd_glob_29, "en/project-center/project-list.mdx": __fd_glob_30, "zh/project-center/create-project.mdx": __fd_glob_31, "zh/project-center/index.mdx": __fd_glob_32, "zh/project-center/project-actions.mdx": __fd_glob_33, "zh/project-center/project-list.mdx": __fd_glob_34, "zh/editor/index.mdx": __fd_glob_35, "zh/editor/project-actions.mdx": __fd_glob_36, "zh/open-api/index.mdx": __fd_glob_37, "en/editor/editor-panels/index.mdx": __fd_glob_38, "en/editor/main-ui/index.mdx": __fd_glob_39, "zh/editor/editor-panels/index.mdx": __fd_glob_40, "zh/editor/main-ui/index.mdx": __fd_glob_41, "en/editor/editor-panels/marker-panel/add-interaction.mdx": __fd_glob_42, "en/editor/editor-panels/marker-panel/add-marker.mdx": __fd_glob_43, "en/editor/editor-panels/ui-panel/add-interaction.mdx": __fd_glob_44, "en/editor/editor-panels/ui-panel/canvas-settings.mdx": __fd_glob_45, "en/editor/editor-panels/ui-panel/page-and-component-management.mdx": __fd_glob_46, "zh/editor/editor-panels/marker-panel/add-interaction.mdx": __fd_glob_47, "zh/editor/editor-panels/marker-panel/add-marker.mdx": __fd_glob_48, "en/editor/editor-panels/model-panel/asset-management.mdx": __fd_glob_49, "en/editor/editor-panels/model-panel/debug-tools.mdx": __fd_glob_50, "en/editor/editor-panels/model-panel/model-settings.mdx": __fd_glob_51, "en/editor/editor-panels/scene-panel/camera-controller.mdx": __fd_glob_52, "en/editor/editor-panels/scene-panel/lighting.mdx": __fd_glob_53, "en/editor/editor-panels/scene-panel/post-processing.mdx": __fd_glob_54, "en/editor/editor-panels/scene-panel/project-settings.mdx": __fd_glob_55, "zh/editor/editor-panels/ui-panel/add-interaction.mdx": __fd_glob_56, "zh/editor/editor-panels/ui-panel/canvas-settings.mdx": __fd_glob_57, "zh/editor/editor-panels/ui-panel/page-and-component-management.mdx": __fd_glob_58, "zh/editor/editor-panels/scene-panel/camera-controller.mdx": __fd_glob_59, "zh/editor/editor-panels/scene-panel/lighting.mdx": __fd_glob_60, "zh/editor/editor-panels/scene-panel/post-processing.mdx": __fd_glob_61, "zh/editor/editor-panels/scene-panel/project-settings.mdx": __fd_glob_62, "zh/editor/editor-panels/model-panel/asset-management.mdx": __fd_glob_63, "zh/editor/editor-panels/model-panel/debug-tools.mdx": __fd_glob_64, "zh/editor/editor-panels/model-panel/model-settings.mdx": __fd_glob_65, });